### ISSUE TITLE
[BUG]  Running d.py alongside dinteractions removes the ability for interactions to handle interaction events

### ISSUE THREAD

**Issue by sa0wii** [interactions-py/interactions.py#419] opened 2022-01-07 13:11 UTC
**Describe the bug**
I am running a bot with both d.py and interactions, as I'm in the middle of migrating everything to interactions. With both of them active at once, the @component decorator breaks and won't do anything.

**Reproducing steps**
These are the steps I took in order to produce this bug, which should be able to be reproduced for everyone else as well.

1. Create a bot, which listens for an interaction, and have it run d.py simultaneously.
2. Use the interaction.

**What's normally expected**
The event should have been registered and the event function should have run.

**What actually happened**
Nothing happened, like the handler wasn't even there.

**Versions**
- [X] I am using discord.py versions 1.7 and below with my code.
    - [ ] I am using 2.0 or higher, or a modified fork.
- [ ] I am using dis-snek with my code.
- [ ] I am not using any of the listed above and am using the library code alone.

**Comment by FayeDel** [comment] 2022-01-07 16:39
Closing because they were assisted in the support server.
Also, this is a dupe of #381.

**Closed as completed by FayeDel** 2022-01-07 16:39 UTC
Labels: bug
