### ISSUE TITLE
[BUG] Starting the bot raises RuntimeError: no running event loop

### ISSUE THREAD

**Issue by mstarongithub** [interactions-py/interactions.py#509] opened 2022-02-11 15:21 UTC
**Describe the bug**
Starting the bot raises the Runtime error "No running event loop"

**Reproducing steps**
Run file containing:
```
import interactions

bot = interactions.Client(token="YourToken")


@bot.command(
    name="HelloWorld",
    description="Hello World",
    scope=server_id,
)
async def hello_world(ctx: interactions.CommandContext):
    await ctx.send("Hello World!")


bot.start()
```

**What's normally expected**
Bot starts up

**What actually happened**
Instead, I received this traceback error given from my Python terminal:

```
Traceback (most recent call last):
  File "/mnt/GamesNProjekts/Projekte/IntegralModBot/main.py", line 4, in <module>
    bot = interactions.Client(token=config.token)
  File "/home/user/.local/share/virtualenvs/IntegralModBot-cTnDASyO/lib/python3.10/site-packages/interactions/client.py", line 76, in __init__
    self._http = HTTPClient(token=token)
  File "/home/user/.local/share/virtualenvs/IntegralModBot-cTnDASyO/lib/python3.10/site-packages/interactions/api/http.py", line 337, in __init__
    self._req = Request(self.token)
  File "/home/user/.local/share/virtualenvs/IntegralModBot-cTnDASyO/lib/python3.10/site-packages/interactions/api/http.py", line 168, in __init__
    self._loop = get_event_loop() if version_info < (3, 10) else get_running_loop()
RuntimeError: no running event loop
```

**Versions**
-  discord-py-interactions package at version 4.0.2
- Python v3.10
- Running on Manjaro Gnome with all packages on their newest version

**Comment by i0bs** [comment] 2022-02-11 17:59
Duplicate of #450

**Comment by EdVraz** [comment] 2022-02-11 18:00
450 is closed and was never merged @goverfl0w

**Closed as completed by i0bs** 2022-02-11 17:59 UTC
Labels: bug
