### ISSUE TITLE
[BUG] unable to pass 0 as an integer argument to a command while having non-0 as the default

### ISSUE THREAD

**Issue by Wizzerinus** [interactions-py/interactions.py#735] opened 2022-04-18 06:32 UTC
### Describe the bug.

No idea if it's a discord issue or a library issue, but

I have a command with an integer argument that has a default value of -1, and can accept any non-negative integer. -1 is different from 0, because 0 means "0 days" and -1 means "use the number from the config file".

So, I did this:
```py
@bot.command(
    name='cooldown',
    description='Put the applicant on cooldown',
    scope=APPLICANTS_ID,
    options=[
        Option(
            name='user',
            description='The user to put on cooldown',
            type=OptionType.USER,
            required=True,
        ),
        Option(
            name='cooldown',
            description='The cooldown duration, 30 days by default',
            type=OptionType.NUMBER,
            required=False,
        )
    ]
)
async def put_on_cooldown(ctx: CommandContext, user: Member, cooldown: int = -1) -> None:
    print('print1', user, cooldown)
    # actual logic not shown
```

And passing 0 to the command does not work:

![image](https://user-images.githubusercontent.com/52964431/163765604-d049f56b-26e3-451c-82c3-0d7b541605b4.png)

![image](https://user-images.githubusercontent.com/52964431/163765635-b78f1a88-035d-4b17-b66c-b302c3d3dd98.png)

### List the steps.

1. Create a slash command with an integer argument that doesn't default to 0.
2. Pass 0 as that argument inside Discord.
3. Get a number other than 0 in the function.

### What you expected.

I expected to get 0 as the argument to the function

### What you saw.

I got the value set as the default value to the function

### What version of the library did you use?

unstable

### Version specification

4.1.1rc1

### Code of Conduct

- [X] I agree to follow the contribution requirements.

**Comment by sillyElvy** [comment] 2022-04-18 06:35
Duplicate of #570

**Closed as completed** 2022-04-18 06:36 UTC
Labels: bug
