### ISSUE TITLE
[BUG] "Object of type Choice is not JSON serializable" on v4.0.2

### ISSUE THREAD

**Issue by sahamone** [interactions-py/interactions.py#453] opened 2022-01-25 07:59 UTC
**Describe the bug**
When executing the code of a bot under the version v4.0.2 of the discord-py-interactions library, an error occurs. This error does not prevent the bot from starting and connecting but it delays the connection.

**Reproducing steps**
To reproduce the bug, you just have to launch a bot with the library in this version. No other library linked to discord is used (ex : py-cord or discord.py)

1. Import the module in Python.
2. Create a client variable for the library.
3. Try creating a slash command.
4. See the traceback error given in the terminal or logger file.

**What's normally expected**
The bot should start normaly, without any problem

**What actually happened**
I have this Traceback in the Terminal

```
--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\mypc\AppData\Local\Programs\Python\Python39\lib\site-packages\interactions\api\http.py", line 249, in request
    async with self._session.request(
  File "C:\Users\mypc\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\client.py", line 1117, in __aenter__   
    self._resp = await self._coro
  File "C:\Users\mypc\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\client.py", line 390, in _request
    data = payload.JsonPayload(json, dumps=self._json_serialize)
  File "C:\Users\mypc\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\payload.py", line 381, in __init__
    dumps(value).encode(encoding),
  File "C:\Users\mypc\AppData\Local\Programs\Python\Python39\lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "C:\Users\mypc\AppData\Local\Programs\Python\Python39\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\mypc\AppData\Local\Programs\Python\Python39\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\mypc\AppData\Local\Programs\Python\Python39\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Choice is not JSON serializable
```

**Versions**
- [ ] I am using discord.py versions 1.7 and below with my code.
    - [ ] I am using 2.0 or higher, or a modified fork.
- [ ] I am using dis-snek with my code.
- [ ] I am not using any of the listed above and am using the library code alone.
- [x] I am using Python v3.9.10
- [x] I am using discord-py-interactions v4.0.2

**Comment by i0bs** [comment] 2022-01-25 16:04
We've noted this as an issue with trying to parse the choice object in command decorators where options are. The next release aims to fix this.

**Comment by UnsignedArduino** [comment] 2022-02-02 03:14
Hey I'm not sure if this is actually the same problem but I would get a similar exception if I had an `Option` that had `choices` in the `options` list for a `command` decorator:
```python
@bot.command(name="bet_coin_flip",
             description="Bet on a coin flip!",
             scope=SCOPE,
             options=[
                 Option(
                     type=OptionType.INTEGER,
                     name="amount",
                     description="How much to bet!",
                     min_value=1,
                     required=True
                 ),
                 Option(
                     type=OptionType.STRING,
                     name="side",
                     description="Side to bet on!",
                     required=True,
                     choices=[
                         Choice(name="heads", value="heads"),
                         Choice(name="tails", value="tails")
                     ]
                 )
             ])
async def bet_coin_flip(ctx: CommandContext, amount: int, side: str):
    pass
```
Changing the list of `Choice`s to plain dictionaries solved my problem.

So this:
```python
choices=[
    Choice(name="heads", value="heads"),
    Choice(name="tails", value="tails")
]
```
Would turn into:
```python
choices=[
    {"name": "heads", "value": "heads"},
    {"name": "tails", "value": "tails"}
]
```

If I used the `Choice` class I would get a gnarly traceback:
```python
--- Logging error ---
Traceback (most recent call last):
  File "E:\CurrencyBot\venv\lib\site-packages\interactions\api\http.py", line 249, in request
    async with self._session.request(
  File "E:\CurrencyBot\venv\lib\site-packages\aiohttp\client.py", line 1117, in __aenter__
    self._resp = await self._coro
  File "E:\CurrencyBot\venv\lib\site-packages\aiohttp\client.py", line 390, in _request
    data = payload.JsonPayload(json, dumps=self._json_serialize)
  File "E:\CurrencyBot\venv\lib\site-packages\aiohttp\payload.py", line 381, in __init__
    dumps(value).encode(encoding),
  File "C:\Users\ckyiu\AppData\Local\Programs\Python\Python39\lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "C:\Users\ckyiu\AppData\Local\Programs\Python\Python39\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\ckyiu\AppData\Local\Programs\Python\Python39\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\ckyiu\AppData\Local\Programs\Python\Python39\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Choice is not JSON serializable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ckyiu\AppData\Local\Programs\Python\Python39\lib\logging\__init__.py", line 1079, in emit
    msg = self.format(record)
  File "C:\Users\ckyiu\AppData\Local\Programs\Python\Python39\lib\logging\__init__.py", line 923, in format
    return fmt.format(record)
TypeError: format() missing 1 required positional argument: 'record'
Call stack:
  File "E:\CurrencyBot\src\main.py", line 216, in <module>
    async def bet_coin_flip(ctx: CommandContext, amount: int):
  File "E:\CurrencyBot\venv\lib\site-packages\interactions\client.py", line 372, in decorator
    [self._loop.run_until_complete(self._synchronize(command)) for command in commands]
  File "E:\CurrencyBot\venv\lib\site-packages\interactions\client.py", line 372, in <listcomp>
    [self._loop.run_until_complete(self._synchronize(command)) for command in commands]
  File "C:\Users\ckyiu\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 629, in run_until_complete
    self.run_forever()
  File "C:\Users\ckyiu\AppData\Local\Programs\Python\Python39\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\Users\ckyiu\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "C:\Users\ckyiu\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "C:\Users\ckyiu\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "E:\CurrencyBot\venv\lib\site-packages\interactions\client.py", line 228, in _synchronize
    await self.__create_sync(payload)
  File "E:\CurrencyBot\venv\lib\site-packages\interactions\client.py", line 145, in __create_sync
    await self._http.create_application_command(
  File "E:\CurrencyBot\venv\lib\site-packages\interactions\api\http.py", line 2036, in create_application_command
    return await self._req.request(Route("POST", url), json=data)
  File "E:\CurrencyBot\venv\lib\site-packages\interactions\api\http.py", line 311, in request
    log.error("".join(traceback.format_exception(type(e), e, e.__traceback__)))
Message: 'Traceback (most recent call last):\n  File "E:\\CurrencyBot\\venv\\lib\\site-packages\\interactions\\api\\http.py", line 249, in request\n    async with self._session.request(\n  File "E:\\CurrencyBot\\venv\\lib\\site-packages\\aiohttp\\client.py", line 1117, in __aenter__\n    self._resp = await self._coro\n  File "E:\\CurrencyBot\\venv\\lib\\site-packages\\aiohttp\\client.py", line 390, in _request\n    data = payload.JsonPayload(json, dumps=self._json_serialize)\n  File "E:\\CurrencyBot\\venv\\lib\\site-packages\\aiohttp\\payload.py", line 381, in __init__\n    dumps(value).encode(encoding),\n  File "C:\\Users\\ckyiu\\AppData\\Local\\Programs\\Python\\Python39\\lib\\json\\__init__.py", line 231, in dumps\n    return _default_encoder.encode(obj)\n  File "C:\\Users\\ckyiu\\AppData\\Local\\Programs\\Python\\Python39\\lib\\json\\encoder.py", line 199, in encode\n    chunks = self.iterencode(o, _one_shot=True)\n  File "C:\\Users\\ckyiu\\AppData\\Local\\Programs\\Python\\Python39\\lib\\json\\encoder.py", line 257, in iterencode\n    return _iterencode(o, 0)\n  File "C:\\Users\\ckyiu\\AppData\\Local\\Programs\\Python\\Python39\\lib\\json\\encoder.py", line 179, in default\n    raise TypeError(f\'Object of type {o.__class__.__name__} \'\nTypeError: Object of type Choice is not JSON serializable\n'
Arguments: ()
Traceback (most recent call last):
  File "E:\CurrencyBot\src\main.py", line 216, in <module>
    async def bet_coin_flip(ctx: CommandContext, amount: int):
  File "E:\CurrencyBot\venv\lib\site-packages\interactions\client.py", line 372, in decorator
    [self._loop.run_until_complete(self._synchronize(command)) for command in commands]
  File "E:\CurrencyBot\venv\lib\site-packages\interactions\client.py", line 372, in <listcomp>
    [self._loop.run_until_complete(self._synchronize(command)) for command in commands]
  File "C:\Users\ckyiu\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "E:\CurrencyBot\venv\lib\site-packages\interactions\client.py", line 228, in _synchronize
    await self.__create_sync(payload)
  File "E:\CurrencyBot\venv\lib\site-packages\interactions\client.py", line 143, in __create_sync
    command: ApplicationCommand = ApplicationCommand(
TypeError: interactions.models.command.ApplicationCommand() argument after ** must be a mapping, not NoneType

Process finished with exit code 1
```
This _would_ cause the bot to crash though, as indicated by the exit code.

**Comment by FayeDel** [comment] 2022-02-02 03:44
Hiya!
Yeah, it somewhat ties into this current issue, and as fl0w said, it will be in the next release. In the meantime, you can use the unstable branch (if you so choose), as it has been patched there :)

**Comment by i0bs** [comment] 2022-02-02 06:37
Closing this issue as it's a duplicate of #409

**Closed as completed by i0bs** 2022-02-02 06:37 UTC
Labels: bug
