### ISSUE TITLE
[BUG] Autodefer not always working

### ISSUE THREAD

**Issue by JoinChang** [interactions-py/interactions.py#1021] opened 2022-08-18 05:34 UTC
### Describe the bug.

This happens when the command is not responded to for three seconds.
![image](https://user-images.githubusercontent.com/35451392/185300899-864ac062-6422-4b5b-9acd-33a791e948a6.png)

Example: https://autocode.com/autocode/threads/how-to-avoid-timeout-errors-when-responding-to-discord-interactions-tutorial-9f4b312c/

### List the steps.

1. Create a slash command and listen to it
2. Create a time-consuming method
3. Command is processing, but few seconds later, Discord returns a new interaction
4. Library doesn't process the interaction normally, returned: `Unknown interaction, with code '10062' and severity '40'`

### What you expected.

Should listen for timeout events.

### What you saw.

```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/interactions/client/models/command.py", line 920, in wrapper
    raise e
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/interactions/client/models/command.py", line 906, in wrapper
    return await coro(ctx, *args, **kwargs)
  File "/Volumes/NTFS/LxBot-Yukimi-Project/lxbot-core/core/adapters/discord/__init__.py", line 39, in _
    await option["func"](self, ctx, **kwargs) # 回调函数
  File "/Volumes/NTFS/LxBot-Yukimi-Project/lxbot-core/modules/bilibili/main.py", line 19, in _
  File "/Volumes/NTFS/LxBot-Yukimi-Project/lxbot-core/core/adapters/discord/__init__.py", line 18, in reply
    await command_send(ctx, **MessageParser().parseArguments(content))
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/interactions/ext/files/files.py", line 356, in command_send
    await Inter_Request.create_interaction_response(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/interactions/ext/files/files.py", line 63, in create_interaction_response
    return await self._req.request(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/interactions/api/http/request.py", line 174, in request
    raise LibraryException(
interactions.api.error.LibraryException: An error occurred:
Unknown interaction, with code '10062' and severity '40'
```

### What version of the library did you use?

release

### Version specification

4.3.0

### Code of Conduct

- [X] I agree to follow the contribution requirements.

**Comment by AstreaTSS** [comment] 2022-08-18 05:43
Hey! This is a common issue with blocking code, which seems to fit in with what you just described.

Blocking code, like really long synchronous tasks (IE the one you described) tends to halt the async "event loop", the logic controlling async as a whole. As interactions.py is async, this means you are effectively halting it from being able to do anything.

For more information, you can [look at the Pycord entry about this](https://docs.pycord.dev/en/stable/faq.html#what-does-blocking-mean). You may need to [run your code in an "executor,"](https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.loop.run_in_executor) or rethink what you are doing in general to use more asynchronous means.

**Comment by Damego** [comment] 2022-08-18 05:43
To increase time limit up to 15 minutes you should defer your interaction via `ctx.defer`

**Comment by JoinChang** [comment] 2022-08-18 05:50
> To increase time limit up to 15 minutes you should defer your interaction via `ctx.defer`

Thank you!

**Comment by JoinChang** [comment] 2022-08-18 08:02
> To increase time limit up to 15 minutes you should defer your interaction via `ctx.defer`

![image](https://user-images.githubusercontent.com/35451392/185342598-2d62a027-17c7-4867-a7bd-61adc37561d2.png)

It still randomly returns this error:
```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/interactions/client/models/command.py", line 920, in wrapper
    raise e
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/interactions/client/models/command.py", line 906, in wrapper
    return await coro(ctx, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/interactions/client/models/utils.py", line 66, in deferring_func
    return await task
  File "/Volumes/NTFS/LxBot-Yukimi-Project/lxbot-core/core/adapters/discord/__init__.py", line 41, in _
    await option["func"](self, ctx, **kwargs) # 回调函数
  File "/Volumes/NTFS/LxBot-Yukimi-Project/lxbot-core/modules/bilibili/main.py", line 18, in _
    await bot.reply(client, message_chain)
  File "/Volumes/NTFS/LxBot-Yukimi-Project/lxbot-core/core/adapters/discord/__init__.py", line 18, in reply
    await command_send(ctx, **MessageParser().parseArguments(content))
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/interactions/ext/files/files.py", line 356, in command_send
    await Inter_Request.create_interaction_response(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/interactions/ext/files/files.py", line 63, in create_interaction_response
    return await self._req.request(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/interactions/api/http/request.py", line 174, in request
    raise LibraryException(
interactions.api.error.LibraryException: An error occurred:
Unknown interaction, with code '10062' and severity '40'
```

**Comment by AstreaTSS** [comment] 2022-08-18 13:14
Again, the issue is likely because your code is blocking - `ctx.defer` can't help out with that.

For further help, please join the interactions.py Discord server and use the help channel.

**Comment by AstreaTSS** [comment] 2022-08-18 14:21
Reopening. Seems like this is an issue with autodefer not working as expected, though, as it seems to fail to defer at times.

**Comment by Damego** [comment] 2022-11-05 15:59
Heya. I think #1012 resolves this issue. Can you try to reproduce your bug on the latest version?

**Comment by JoinChang** [comment] 2022-11-05 16:42
> Heya. I think #1012 resolves this issue. Can you try to reproduce your bug on the latest version?

Thanks, it works properly!

But it still randomly raise this error when processing time-consuming command, but `@autodefer` itself works properly.
![image](https://user-images.githubusercontent.com/35451392/200131322-3f383415-27de-48c0-909b-2f63292dcbb9.png)
![image](https://user-images.githubusercontent.com/35451392/200131555-7389f000-a9c0-480e-9f29-2065d59b45da.png)

**Comment by sillyElvy** [comment] 2022-11-05 16:43
> > Heya. I think #1012 resolves this issue. Can you try to reproduce your bug on the latest version?
> 
> Thanks, it works properly!
> 
> But it still randomly raise this error when processing time-consuming command, but `@autodefer` itself works properly.
> ![image](https://user-images.githubusercontent.com/35451392/200131322-3f383415-27de-48c0-909b-2f63292dcbb9.png)
> 

Try setting the time after autodefer fires to smth lower, sometimes it is a bit slow

**Comment by JoinChang** [comment] 2022-11-05 16:52
> > > Heya. I think #1012 resolves this issue. Can you try to reproduce your bug on the latest version?
> > 
> > 
> > Thanks, it works properly!
> > But it still randomly raise this error when processing time-consuming command, but `@autodefer` itself works properly.
> > ![image](https://user-images.githubusercontent.com/35451392/200131322-3f383415-27de-48c0-909b-2f63292dcbb9.png)
> 
> Try setting the time after autodefer fires to smth lower, sometimes it is a bit slow

I tried lower delay params, and I'm didn't processing time-consuming command, but it still raised Unknown Interactions exception:
![image](https://user-images.githubusercontent.com/35451392/200131801-cd274155-143a-40af-858e-fe7e8a7f157a.png)
![image](https://user-images.githubusercontent.com/35451392/200131819-94c0986e-2f9b-465c-bfe4-a44cd7be353e.png)

**Comment by sillyElvy** [comment] 2022-11-05 16:53
> > > > Heya. I think #1012 resolves this issue. Can you try to reproduce your bug on the latest version?
> > > 
> > > 
> > > Thanks, it works properly!
> > > But it still randomly raise this error when processing time-consuming command, but `@autodefer` itself works properly.
> > > ![image](https://user-images.githubusercontent.com/35451392/200131322-3f383415-27de-48c0-909b-2f63292dcbb9.png)
> > 
> > Try setting the time after autodefer fires to smth lower, sometimes it is a bit slow
> 
> I tried lower delay params, but it still raised Unknown Interactions exception:
> ![image](https://user-images.githubusercontent.com/35451392/200131801-cd274155-143a-40af-858e-fe7e8a7f157a.png)
> ![image](https://user-images.githubusercontent.com/35451392/200131819-94c0986e-2f9b-465c-bfe4-a44cd7be353e.png)
> 

That's weird, @Toricane didn't you want to rewrite it?

**Comment by LordOfPolls** [comment] 2023-04-10 12:15
Resolved in v5

**Closed as completed by LordOfPolls** 2023-04-10 12:15 UTC
Labels: bug
