### ISSUE TITLE
[BUG] Sending a message from context menu not working

### ISSUE THREAD

**Issue by thrzl** [interactions-py/interactions.py#397] opened 2021-12-22 14:26 UTC
**Describe the bug**
using this code (get_user just goes to a seperate api, returns data very similar to discord's user endpoint):
```py
@bot.command(
    type=ApplicationCommandType.USER, name="lookup user.", scope=879747655197139005
)
async def lookup_menu(ctx: CommandContext):  # user commands return the member
    user_id = ctx.target.id
    u = get_user(int(user_id))
    if not u:
        f = dict(name="user not found.", value="the user you are looking for does not exist, check the id.")
        embed=Embed(color=0x2f3136, fields=[f])
        return await ctx.send(embeds=[embed])
    
    a = dict(name=f"{u['username']}#{u['disc']}", icon_url=u["avatar"])
    fs = [
        dict(name="id", value=u["id"]),
    ]
    if u["is_banned"]:
        fs.append(dict(name="reason of ban", value=u["reason"]))
        fs.append(dict(name="proof", value=u["proof"]))
    f = {"text": f"requested by {ctx.author.user.username}", "icon_url": ctx.author.user.avatar}
    embed = Embed(color=0x2f3136, thumbnail={"url": u["avatar"]}, author=a, footer=f, fields=fs)
    await ctx.send(embeds=[embed])
```

However, the bot does not send the message. It returns a message object, but the message object is missing an ID.

I am especially confused as to create this command I literally copy & pasted my slash command, added the User type, and changed the name to create this block.

I tried deferring, only to be met with (a long time later, ) "this interaction failed."

There are no errors anywhere, and print debugging (even after the `await ctx.send`) show that everything is working.

**Reproducing steps**
These are the steps I took in order to produce this bug, which should be able to be reproduced for everyone else as well.

1. Import the module in Python.
2. Create a client variable for the library.
3. Create a context menu
4. See "this interaction failed" in discord.

**What's normally expected**
When I create a context menu command, the command should send the embed detailing the user info.

**What actually happened**
Instead, I received a `This interaction failed` message with no errors in the code:

![image](https://user-images.githubusercontent.com/73202594/147107668-f940056f-e365-46a4-b25e-c8c37a98e90c.png)

**Versions**
- [ ] I am using discord.py versions 1.7 and below with my code.
    - [ ] I am using 2.0 or higher, or a modified fork.
- [ ] I am using dis-snek with my code.
- [x] I am not using any of the listed above and am using the library code alone.

**Comment by sillyElvy** [comment] 2021-12-22 16:09
Try not to send the embed as list, do instead `return await ctx.send(embeds=embed)`

(at least I was not able to reproduce that when I tried it like that)

Also I think that the fields `title` and `description` are required for embeds

**Comment by thrzl** [comment] 2021-12-22 18:31
Thanks for the reply, but after trying both of your fixes independently and then together, I still seem to be having the same issue. Do you have any more ideas?

**Comment by Toricane** [comment] 2021-12-22 18:41
I tried this below, and it worked:
```py
@bot.command(
    type=interactions.ApplicationCommandType.USER,
    name="lookup user.",
    scope=874781880489222154,
)
async def lookup_menu(
    ctx: interactions.CommandContext,
):  # user commands return the member
    embed = interactions.Embed(color=0x2F3136, title="User Lookup", description="hi")
    await ctx.send(embeds=[embed])
```
Try using the embed models for the thumbnail, author, footer, and fields in [here](https://discord-interactions.readthedocs.io/en/latest/api.models.message.html?highlight=Embed#message-models). Scroll all the way down

**Comment by i0bs** [comment] 2021-12-22 18:59
**What's the problem?**
The main issue I'm seeing is that you're trying to use dictionary types for kwarg fields that do not allow that. `fields`, `footer` and `author` all use their own respective objects [`EmbedField`](https://i.imgur.com/6MdYST7.png), [`EmbedFooter`](https://i.imgur.com/uKb5SoH.png) and [`EmbedAuthor`](https://i.imgur.com/g28jVTt.png).

**Why did we choose to do this instead of easier solutions?**
This was chosen in favor for an API schema-strict design. The official Discord Developers documentation considers these fields to be [objects of their own,](https://i.imgur.com/um1BYX2.png) so we inherited this into the 4.0 architecture.

**Comment by thrzl** [comment] 2021-12-22 19:13
The reason that I was using dict types is because I was repeatedly getting this error:
```py
    dumps(value).encode(encoding),
  File "/usr/lib/python3.8/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type EmbedAuthor is not JSON serializable
```

Switching back to classes, I still receive this error.

**Comment by i0bs** [comment] 2021-12-22 19:24
That error should not be producing on the latest build `4.0.1`. Can you ensure that you have it as `author=interactions.EmbedAuthor(name="author here")`?

You also don't have the full traceback error stack, so I can't gather any meaningful insight besides `TypeError` being a thrown exception. Please include the rest of the error trace.

**Comment by thrzl** [comment] 2021-12-22 19:38
Apologies for not including a full traceback.

I can confirm that my `EmbedAuthor` is written similarly to yours, in case I'm incorrect, here is mine currently:
```py
author=interactions.EmbedAuthor(name=f"{u['username']}#{u['disc']}")
```

```py
ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='Task-19' coro=<lookup_menu() done, defined at bot.py:58> exception=TypeError('Object of type EmbedAuthor is not JSON serializable')>
Traceback (most recent call last):
  File "bot.py", line 79, in lookup_menu
    await ctx.send(embeds=embed)
  File "/home/mikey/.cache/pypoetry/virtualenvs/fermi-rg9EyTQF-py3.8/lib/python3.8/site-packages/interactions/context.py", line 260, in send
    await func()
  File "/home/mikey/.cache/pypoetry/virtualenvs/fermi-rg9EyTQF-py3.8/lib/python3.8/site-packages/interactions/context.py", line 253, in func
    await self.client.create_interaction_response(
  File "/home/mikey/.cache/pypoetry/virtualenvs/fermi-rg9EyTQF-py3.8/lib/python3.8/site-packages/interactions/api/http.py", line 2058, in create_interaction_response
    return await self._req.request(
  File "/home/mikey/.cache/pypoetry/virtualenvs/fermi-rg9EyTQF-py3.8/lib/python3.8/site-packages/interactions/api/http.py", line 200, in request
    async with self.session.request(
  File "/home/mikey/.cache/pypoetry/virtualenvs/fermi-rg9EyTQF-py3.8/lib/python3.8/site-packages/aiohttp/client.py", line 1117, in __aenter__
    self._resp = await self._coro
  File "/home/mikey/.cache/pypoetry/virtualenvs/fermi-rg9EyTQF-py3.8/lib/python3.8/site-packages/aiohttp/client.py", line 390, in _request
    data = payload.JsonPayload(json, dumps=self._json_serialize)
  File "/home/mikey/.cache/pypoetry/virtualenvs/fermi-rg9EyTQF-py3.8/lib/python3.8/site-packages/aiohttp/payload.py", line 381, in __init__
    dumps(value).encode(encoding),
  File "/usr/lib/python3.8/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type EmbedAuthor is not JSON serializable
```

**Comment by i0bs** [comment] 2021-12-22 19:43
Can you check if `u["username"}` and `u["desc"]` are string-safe? When an HTTP request is made using our models, we rely on an internal attribute `_json` inside each object to directly convert to a dictionary that can then be sent to the Web API. The only way that a conversion error with an object type could occur is if the serialization process is not respected, and something that is not respected to the original attributes are being put in. 

> (get_user just goes to a seperate api, returns data very similar to discord's user endpoint)

I have no clue what `get_user()` actually returns, so it's a hunch and even if you do say that it gives information similar to Discord's user endpoint, I won't be able to confirm for sure unless I have a basis to work off of.

**Comment by thrzl** [comment] 2021-12-22 19:55
Here's an example of data `get_user()` might return:
```json
{
    "avatar": "https://cdn.discordapp.com/avatars/536644802595520534/4dfd4b1a38e9c4e47d401bc446a0628b.webp",
    "disc": "4258",
    "error": false,
    "id": 536644802595520534,
    "is_banned": true,
    "issue_date": "Fri, 27 Aug 2021 21:35:08 GMT",
    "message": null,
    "proof": "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    "reason": "you know the rules",
    "severity": 1,
    "username": "thrizzle."
}
```
`u["username"]` and `u["disc"]` are both strings, and neither have any characters that cannot be entered on a QWERTY keyboard (e.g. fancy text).

`get_user()` returns none if the request errors, hence the check at the beginning of the original code. I also have checked manually using print statements the value of get_user, which always returns what is expected.

**Comment by i0bs** [comment] 2021-12-22 19:59
From what I understand, two errors can come based off of conditions for the method:

- You can have an issue with `fields` if the data is returned as `None` since you're using a dict conversion. (This is me assuming you're not using a class object here which you probably are using now)
- There is a conversion issue running with the way that the `author` field is presented. Can you try `interactions.EmbedAuthor(...)._json`?

**Comment by thrzl** [comment] 2021-12-22 20:04
`EmbedAuthor._json` returns 
```json
{
	"name": "Carl-bot#1536",
	"icon_url": "https://cdn.discordapp.com/avatars/235148962103951360/cececd50fdc87b29929e65c768f24ad6.png"
}
```

A quick note: when the objects are `dict` objects, the code doesn't error, it just doesn't send anything.

**Comment by i0bs** [comment] 2022-01-05 12:28
Closing this issue, `EmbedAuthor` now sends correctly.

**Closed as completed by i0bs** 2022-01-05 12:28 UTC
Labels: bug
