### ISSUE TITLE
[REQUEST] Extract arguments from error

### ISSUE THREAD

**Issue by sami0596** [interactions-py/interactions.py#506] opened 2022-02-10 22:15 UTC
**What is the feature you're proposing?**
Extract arguments from error, like the actual command the user entered with all arguments So we can debug

**Comment by i0bs** [comment] 2022-02-11 00:08
This is a dupe of something on our 2022 roadmap and is planned for 4.1.

**Closed as completed by i0bs** 2022-02-11 00:08 UTC
Labels: documentation, enhancement
