### ISSUE TITLE
[BUG] SelectMenu cannot be added to ActionRow

### ISSUE THREAD

**Issue by Mayerch1** [interactions-py/interactions.py#523] opened 2022-02-15 13:09 UTC
**Describe the bug**
When trying to add a SelectMenu to an ActionRow, an `AttributeError` is raised.

**Reproducing steps**
I'm on the unstable branch, with `pip freeze` giving the following version number
`discord-py-interactions @ git+https://github.com/interactions-py/library@042a848cf9f89a8857caef63870c2111718d2aa3`

When trying to add any SelectMenu to an ActionRow, the bot crashes. The following code is an (almost) minimal example crashing on the 2nd to last line, there's no need for a bot instance for this to happen.

```
import interactions

options = [
    interactions.SelectOption(
        label='Overview Page',
        description='List all available commands',
        value='overview',
        default=True
    ),
    interactions.SelectOption(
        label='Parameters Page',
        description='Explain the different command parameters',
        value='parameters',
        default=False
    ),
]
help_selection = interactions.SelectMenu(
        custom_id='help_navigation',
        options=options,
        placeholder='Please select a category',
        min_values=1,
        max_values=1,
)

row_2 = interactions.ActionRow(components=[help_selection])
print(row_2)
```

**What's normally expected**
The ActionRow should be created and then outputted to console in the print statement.

**What actually happened**
```
Traceback (most recent call last):
  File "test.py", line 28, in <module>
    row_2 = interactions.ActionRow(components=[help_selection])
  File "/home/user/.local/lib/python3.8/site-packages/interactions/models/component.py", line 341, in __init__
    component._json["options"] = [option._json for option in component._json["options"]]
  File "/home/user/.local/lib/python3.8/site-packages/interactions/models/component.py", line 341, in <listcomp>
    component._json["options"] = [option._json for option in component._json["options"]]
AttributeError: 'dict' object has no attribute '_json'
```

The bug was briefly discussed on discord at https://discord.com/channels/789032594456576001/942850793172774984.
Based on that discussion, the method was likely broken within the last few commits.

**Versions**
- [ ] I am using discord.py versions 1.7 and below with my code.
    - [ ] I am using 2.0 or higher, or a modified fork.
- [ ] I am using dis-snek with my code.
- [x] I am not using any of the listed above and am using the library code alone.

**Comment by sillyElvy** [comment] 2022-02-15 13:11
Delta changed how select options are serialised, that probably broke it

**Comment by Jalancar** [comment] 2022-02-15 15:42
Can confirm that I updated to latest unstable branch last night and it broke mine also

**Comment by sillyElvy** [comment] 2022-02-15 15:44
I think this [commit](https://github.com/interactions-py/library/commit/ca60c2e4d2c4aa18aa2eed11589655f654e81786) broke it

**Comment by i0bs** [comment] 2022-02-15 15:46
That commit is logically correct, but i'll look into the issue.

**Comment by sillyElvy** [comment] 2022-02-15 15:47
ik, the issue is the commit breaks our code what was converting the object before, because now it is converted already

**Comment by FayeDel** [comment] 2022-02-15 15:58
In reference to that commit, it effectively already does the same thing, but its refactored to not use the `._json` attr when assigning options for redundancy
But before that commit, select menus broke when they're not in an action row (without doing explicit `_json` of course)

Moreover, this is (yet again) an actionrow recursive issue that's fixed in the latest commit (2dc1242)

**Comment by i0bs** [comment] 2022-02-15 16:00
Post-4.1, we should begin looking into a universalised algorithm for model conversion. [This is a comment I made in the past](https://github.com/interactions-py/library/issues/406#issuecomment-1005647875) for what worked best in helping solve these kinds of issues.

**Comment by sillyElvy** [comment] 2022-02-15 18:32
This should be fully fixed now.

**Closed as completed by sillyElvy** 2022-02-15 18:32 UTC
Labels: bug
