### ISSUE TITLE
[BUG] This is stranger behaviour than a bug.

### ISSUE THREAD

**Issue by AlphaGaming7780** [interactions-py/interactions.py#1514] opened 2023-08-05 13:37 UTC
### Library Version

5.8.0

### Describe the Bug

OK, I have this code : 
```python
artSuggestionChannel = bot.get_channel(config["ArtValidationChannelId"])
posts = artSuggestionChannel.get_posts(exclude_archived=True)
for post in posts:
	print(post)
	try:
		if(":green_square:" in post.initial_post.embeds[0].fields[2].value):
			print(reactions = post.initial_post.reactions)
	except:
		print(post.initial_post)
```

the output of this is : 
```
GuildForumPost(id=1137046357383839795, name='Atomium', type=<ChannelType.GUILD_PUBLIC_THREAD: 11>)
None
GuildForumPost(id=1134493438587445349, name='Create a suggestion.', type=<ChannelType.GUILD_PUBLIC_THREAD: 11>)
None
```

but when I “load” the message like this code : 
```python
artSuggestionChannel = bot.get_channel(config["ArtValidationChannelId"])
posts = artSuggestionChannel.get_posts(exclude_archived=True)
for post in posts:
	print(post)
	print(await post.fetch_messages())
	try:
		if(":green_square:" in post.initial_post.embeds[0].fields[2].value):
			print(reactions = post.initial_post.reactions)
	except:
		print(post.initial_post)
```
The output of this is :
```
GuildForumPost(id=1137046357383839795, name='Atomium', type=<ChannelType.GUILD_PUBLIC_THREAD: 11>)
[Message(id=1137046357383839795)]
Message(id=1137046357383839795)
GuildForumPost(id=1134493438587445349, name='Create a suggestion.', type=<ChannelType.GUILD_PUBLIC_THREAD: 11>)
[Message(id=1137369556814405632), Message(id=1134493438587445349)]
Message(id=1134493438587445349)
```

IDK if it's a bug, but would be nice to, warn people when using `.initial_post` to "load" the message before or something like that.

### Steps to Reproduce

UP

### Expected Results

UP x2

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.
- [X] I have attempted to debug this myself, and I believe this issue is with the library

**Comment by AstreaTSS** [comment] 2023-08-05 16:29
It's not a bug (the channel is properly marked as being optional/potentially None), it's just how getting from the cache works. That being said, perhaps the docs could be clearer about cache use potentially.

**Comment by AlphaGaming7780** [comment] 2023-08-05 17:34
Okay, thank you for the response.

But is there a better way to make my code work without using this line : `print(await post.fetch_messages())` ?

**Comment by AstreaTSS** [comment] 2023-08-05 17:37
The ID of the channel is also the ID of the first message sent in it. You can do a simple fetch to get it from here.

If you wish for more help, I highly suggest you join the support server and ask there.

**Closed as completed** 2023-08-05 23:00 UTC
