### ISSUE TITLE
[BUG] option type 9 returning string instead of User/Role object. 

### ISSUE THREAD

**Issue by sillyElvy** [interactions-py/interactions.py#366] opened 2021-11-18 18:26 UTC
**Describe the bug**
When I try to get a User or Role object from option type 9 I'm instead receiving a string of the id.

**Reproducing steps**

```py
ch_perm_edt_opt = [
        {
            "name": "channel",
            "description": "the channel update permissions on",
            "type": 7,
            "required": True,
        },
        {
            "name": "role_or_user",
            "description": "the role or user to give special permissions over a channel",
            "type": 9,
            "required": True,
        },
    ]

    @cog_ext.cog_subcommand(base="server", subcommand_group="channel", name="permission_edit", options=ch_perm_edt_opt,
                            description="edits the permissions a user or a role has in a specific channel")
    async def _channel_permission_edit(self, ctx: SlashContext,
                                       channel: Union[discord.TextChannel, discord.VoiceChannel],
                                       role_or_user: Union[discord.Role, discord.Member]):
        if not ctx.author.guild_permissions.manage_channels and not ctx.author.guild_permissions.manage_permissions:
            raise discord.ext.commands.MissingPermissions(missing_perms=["manage_channels", "manage_permissions"])

        else:
            await ctx.defer(hidden=False)

        if isinstance(channel, discord.TextChannel):
            utils.LOGGER.debug(f"Test: {isinstance(role_or_user, str)} \n value: {role_or_user}")
        ... 
        perm_overwrite = {
                    role_or_user: perm
        }
        await channel.edit(overwrites=perm_overwrite,
                                    reason=f"User {ctx.author.name} used the channel-permission-edit command!")
        await perms.channel.send(f"Done, channel '{channel.name} has been edited!", delete_after=180)
```

**What's normally expected**
I expected the channel to be edited without any error

**What actually happened**
[Instead, I received this traceback error](https://cdn.discordapp.com/attachments/910942906540494898/910943657652256768/unknown.png), which really confused me, because I expected `role_or_user`to be a role or a user, so I totally did not understand why that error appeared.

After a bit of research, I noticed, that `utils.LOGGER.debug(f"Test: {isinstance(role_or_user, str)}")` returned True, so I opened a [thread ](https://ptb.discord.com/channels/789032594456576001/910942906540494898/910942920998256660)on your discord server. There I got told to check the value of `role_or_user`. I did `utils.LOGGER.debug(f"Test: {isinstance(role_or_user, str)} \n value: {role_or_user}")` and it returned '744218316167708773' as value. 

That seems to be the id of the user or role, so *theoretically* I am able to get it with the builtin methods, but because I don't know if it is a user or a role I would have to execute two methods and that's why I do not think that this is intended

**Versions**
- [x] I am using discord.py versions 1.7 and below with my code.
    - [ ] I am using 2.0 or higher, or a modified fork.
- [ ] I am using dis-snek with my code.
- [ ] I am not using any of the listed above and am using the library code alone.

**Comment by FayeDel** [comment] 2021-11-18 19:22
Yeah... this wasn't intended 😓 

There was no built-in lib data conversion for the mentionable type, so it defaulted to the ID snowflake that you saw.

**Comment by sillyElvy** [comment] 2021-11-18 19:26
Will you fix it/create it?

**Comment by FayeDel** [comment] 2021-11-18 19:30
I've fixed it on my end, it works as intended, but there'll be no official release as fl0w pointed out earlier.

**Comment by sillyElvy** [comment] 2021-11-18 19:33
OK....

**Comment by FayeDel** [comment] 2021-12-07 22:20
Closing in favor of #288.

**Closed as completed by FayeDel** 2021-12-07 22:20 UTC
Labels: bug
