### ISSUE TITLE
Heartbeat dropping crashes the bot until manually restarted

### ISSUE THREAD

**Issue by dxf** [interactions-py/interactions.py#430] opened 2022-01-13 09:40 UTC
This has been discussed in the Discord server, but I thought I'd file an issue for the sake of completeness.

When a bot can't get a heartbeat, there's no connection logic to reconnect the bot afterwards. This means that bots, even on stable connections (I'm using a Contabo VPS), can have trouble staying online for any extended period of time.

For now, as a bodge, I'm testing using GNU timeout to restart my bot by force as a pre-emptive measure - if anyone wants the shell script, let me know

**Comment by CBradell** [comment] 2022-01-19 05:13
I am experiencing the same issue. My bot will stop working as soon as it can't get a heartbeat and is needing to be restarted about once an hour right now. :(

**Comment by CBradell** [comment] 2022-01-19 05:14
Also, I am using an Azure VM; should be a pretty stable connection.

**Comment by i0bs** [comment] 2022-01-19 05:22
I believe I know the cause for this issue and it's a simple fix, however, we're planning on refactoring the gateway which would eliminate this problem anyhow. (Or at least in theory, it would.) There's a current experiment you can try running to see if this produces the issue or not:

- Go to `gateway.py`
- Find the `Heartbeat` class
- Remove the `- random()` arithmetic math. 

What I believe is happening is that for every `HEARTBEAT` packet the Gateway recognises (when the websocket connection remains to be valid) we run the threading `Event`'s main protocol all over again, and it keeps on iterating the `random()` call as a completely new value. Now, this call produces a float anywhere between 0 and 1 and it's theoretically very small of a difference. However, a heartbeat is typically sent once every 43-45 seconds. If you do the math, and let's assume the average of `random()` is `0.10`, it would only take ~45 minutes before the heartbeat is completely out of alignment. This is because we have a `wait()` call happening on the thread, and then it adds an additional micro value. Because of this there's accumulation over time, and then eventually leads to a zombified connection.

This is honestly an oversight on my part, and we can probably do away entirely with the subtraction of the random value. We did this, however, because it worked well for most cases that needed us to check for jitter. The Gateway *does* handle network latency between you (the client) and the server, but we didn't know just how precise it was. The Developers documentation also mentioned that it was okay for us to do this, so we bit the bullet and did it anyhow.

**Comment by CBradell** [comment] 2022-01-19 05:26
> There's a current experiment you can try running to see if this **produces** the issue or not:
> 
> * Go to `gateway.py`
> * Find the `Heartbeat` class
> * Remove the `- random()` arithmetic math.

Do you mean this will introduce the error? Or that it should fix it? I am available to try this and let you know.

**Comment by CBradell** [comment] 2022-01-19 13:35
Just FYI, I removed the - random() arithmetic math from the Heartbeat class and still am having the same issue.

**Comment by i0bs** [comment] 2022-01-19 13:40
Does the bot crash more, less or the same amount of frequency?

**Comment by CBradell** [comment] 2022-01-19 13:44
I left my bot running overnight and it wasn't working when I woke up. I'll restart it, monitor, and let you know. I can record some average times to crashing for you.

**Comment by chrisae9** [comment] 2022-01-19 15:16
Same issue after the fix:
01/18/2022 07:46:37 PM INFO: [<module>] Starting bot.
01/18/2022 09:42:19 PM ERROR: [run] The client was unable to send a heartbeat, closing the connection.

01/19/2022 12:35:26 AM INFO: [<module>] Starting bot.
01/19/2022 02:45:32 AM ERROR: [run] The client was unable to send a heartbeat, closing the connection.

Seems to be crashing every 2 hours.

**Comment by CBradell** [comment] 2022-01-19 15:33
I also timed my first crash at ~2 hours just now.

**Comment by i0bs** [comment] 2022-01-20 02:35
I've identified the cause of the bug during my testing and will be addressed for next release.

**Comment by CBradell** [comment] 2022-01-20 22:06
Is this a quick fix still; something I can go ahead and change to get the bot working? Or will we need to wait for release?

Thanks for checking into this and identifying the issue!

**Comment by i0bs** [comment] 2022-01-25 03:49
We've initiated a PR that will address this. See issue #452 that goes into the specific details of why this is happening. Because another issue has been set up for this, we will be closing this one. I highly recommend to take any conversations from here to there.

**Closed as completed by i0bs** 2022-01-25 03:49 UTC
Labels: bug
