### ISSUE TITLE
[REQUEST] Separate dev requirements into requirements-dev.txt

### ISSUE THREAD

**Issue by telugu-boy** [interactions-py/interactions.py#414] opened 2022-01-03 20:04 UTC
**What is the feature you're proposing?**
Move dependencies such as `black`, `flake8`, `isort`, .... into their own requirements-dev.txt file. Installing these dependencies as an end-user of the library is a waste of space and time.

**Comment by i0bs** [comment] 2022-01-03 20:06
Duplicate of #398

**Closed as completed by i0bs** 2022-01-03 20:06 UTC
Labels: documentation, duplicate, enhancement
